name: Test Rust MySQL Client integrations

on:
  pull_request:
    paths:
      - 'go/**'
      - 'integration-tests/**'

concurrency:
  group: ci-rust-mysql-client-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mysql_client_integrations_job:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    name: Run test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy go package
        run: cp -r ./go ./integration-tests/go
      - name: Test rust mysql client integrations
        uses: ./.github/actions/rust-client-test
